# Tensors and Operations
* [source site](https://www.tensorflow.org/beta/tutorials/eager/basics)

In [1]:
import tensorflow as tf

In [2]:
print(tf.add(1,2))

tf.Tensor(3, shape=(), dtype=int32)


In [3]:
print(tf.add([1,2], [3,4]))

tf.Tensor([4 6], shape=(2,), dtype=int32)


In [4]:
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [6]:
print(tf.reduce_sum([1, 2, 6]))

tf.Tensor(9, shape=(), dtype=int32)


In [7]:
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [8]:
x = tf.matmul([[1]], [[2,3]])
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [9]:
print(x.shape)

(1, 2)


In [10]:
print(x.dtype)

<dtype: 'int32'>


In [11]:
import numpy as np

In [12]:
ndarray = np.ones([3,3])

In [16]:
print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, [42])
print(tensor)

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [17]:
print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [18]:
print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [19]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
True
Is the Tensor on GPU #0:  
True


In [21]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.matmul(x, x)

    result = time.time()-start

    print("10 loops: {:0.2f}ms".format(1000*result))

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
    x = tf.random.uniform([10000, 10000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

# Force execution on GPU #0 if available
if tf.test.is_gpu_available():
    print("On GPU:")
    with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
        x = tf.random.uniform([10000, 10000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
10 loops: 45302.97ms
On GPU:
10 loops: 0.45ms


## how to deal with dataset
* See [guide](https://www.tensorflow.org/guide/datasets#reading_input_data)

In [22]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [23]:
ds_tensors

<TensorSliceDataset shapes: (), types: tf.int32>

In [24]:
ds_file

<TextLineDatasetV2 shapes: (), types: tf.string>

In [25]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [26]:
ds_tensors

<BatchDataset shapes: (None,), types: tf.int32>

In [27]:
ds_file

<BatchDataset shapes: (None,), types: tf.string>

In [28]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)

print('\nElements in ds_file:')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor([ 9 16], shape=(2,), dtype=int32)
tf.Tensor([36 25], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)
