# Custom layers
* [source site](https://www.tensorflow.org/beta/tutorials/eager/custom_layers)

In [1]:
import tensorflow as tf

In [2]:
layer = tf.keras.layers.Dense(100) # out dimension, weight matrix will be 100 x 100

In [24]:
layer(tf.zeros([10,10, 100]))

<tf.Tensor: id=202, shape=(10, 10, 100), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        

In [36]:
layer = tf.keras.layers.Dense(10, input_shape=(None, 5)) # out dimension, weight matrix will be 5 x 10

In [37]:
layer(tf.zeros([3,5])) # 3 x 5 matmul 5 x 10 -> 3 x 10 matrix

<tf.Tensor: id=340, shape=(3, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [38]:
layer.variables

[<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.42282605, -0.41934448,  0.07773662,  0.50642365, -0.3064758 ,
         -0.127895  , -0.2520819 ,  0.48849994, -0.6138225 ,  0.25252646],
        [-0.3202074 ,  0.08669531, -0.5029659 , -0.44846758,  0.47160167,
         -0.5929061 ,  0.37337214,  0.13906783, -0.56209564, -0.47424018],
        [ 0.08147818, -0.05058903, -0.5571285 , -0.2602969 ,  0.06184709,
          0.3634516 ,  0.12791431, -0.48855984, -0.3734702 , -0.4377706 ],
        [ 0.53691477, -0.58809334, -0.3347557 , -0.06593752, -0.54093695,
         -0.4010741 ,  0.144225  ,  0.20093483, -0.44791478, -0.5612841 ],
        [-0.204175  ,  0.324485  ,  0.00564104,  0.42664462, -0.4446187 ,
          0.16988117, -0.49654776,  0.2605157 ,  0.4233305 , -0.21020973]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [40]:
layer.kernel

<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.42282605, -0.41934448,  0.07773662,  0.50642365, -0.3064758 ,
        -0.127895  , -0.2520819 ,  0.48849994, -0.6138225 ,  0.25252646],
       [-0.3202074 ,  0.08669531, -0.5029659 , -0.44846758,  0.47160167,
        -0.5929061 ,  0.37337214,  0.13906783, -0.56209564, -0.47424018],
       [ 0.08147818, -0.05058903, -0.5571285 , -0.2602969 ,  0.06184709,
         0.3634516 ,  0.12791431, -0.48855984, -0.3734702 , -0.4377706 ],
       [ 0.53691477, -0.58809334, -0.3347557 , -0.06593752, -0.54093695,
        -0.4010741 ,  0.144225  ,  0.20093483, -0.44791478, -0.5612841 ],
       [-0.204175  ,  0.324485  ,  0.00564104,  0.42664462, -0.4446187 ,
         0.16988117, -0.49654776,  0.2605157 ,  0.4233305 , -0.21020973]],
      dtype=float32)>

In [41]:
 layer.bias

<tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [42]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    # build kernel when input shape determined
    def build(self, input_shape):
        self.kernel = self.add_variable("kernel",
                                    shape=[int(input_shape[-1]),
                                           self.num_outputs])
    
    def call(self, input):
        return tf.matmul(input, self.kernel)

In [48]:
layer = MyDenseLayer(10)

In [49]:
layer(tf.zeros([5,3]))

<tf.Tensor: id=400, shape=(5, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [50]:
print(layer.trainable_variables)

[<tf.Variable 'my_dense_layer_1/kernel:0' shape=(3, 10) dtype=float32, numpy=
array([[-0.57586384,  0.5021826 ,  0.30060184,  0.44381285,  0.39920855,
         0.48386204,  0.61279786, -0.356461  ,  0.6187074 ,  0.6523614 ],
       [ 0.24169934, -0.04340649, -0.42042175,  0.43719685, -0.33446756,
         0.48524868,  0.6518729 ,  0.4041115 , -0.05547398,  0.4844849 ],
       [ 0.6020634 ,  0.5684643 , -0.5870585 ,  0.45037806,  0.36038303,
        -0.5741495 , -0.1245079 , -0.2212202 ,  0.55753446, -0.47789237]],
      dtype=float32)>]


In [51]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters

        self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
        self.bn2a = tf.keras.layers.BatchNormalization()

        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()

        self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()

    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)

        x = self.conv2c(x)
        x = self.bn2c(x, training=training)

        x += input_tensor
        return tf.nn.relu(x)


In [63]:
block = ResnetIdentityBlock(2, [1, 2, 3])

In [64]:
print(block(tf.zeros([1, 5, 5, 3])))

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 5, 5, 3), dtype=float32)


In [70]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1),
                                                    input_shape=(
                                                        None, None, 3)),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(2, 1,
                                                    padding='same'),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(3, (1, 1)),
                             tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=4051, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [79]:
conv_layer = tf.keras.layers.Conv2D(32, (3, 3),input_shape=(None, None, 3))

In [80]:
conv_layer(tf.zeros([1,6,6,3]))

<tf.Tensor: id=4193, shape=(1, 4, 4, 32), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,