# Automatic differentiation and gradient tape
* [source site](https://www.tensorflow.org/beta/tutorials/eager/automatic_differentiation)

In [1]:
import tensorflow as tf

In [2]:
x = tf.ones((2,2))

In [3]:
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

In [4]:
print(y)

tf.Tensor(4.0, shape=(), dtype=float32)


In [5]:
print(z)

tf.Tensor(16.0, shape=(), dtype=float32)


In [6]:
dz_dx = t.gradient(z, x)

In [7]:
print(dz_dx)

tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [13]:
for i in [0, 1]:
    for j in [0, 1]:
        assert dz_dx[i][j].numpy() == 8.0

In [15]:
x = tf.ones((2,2))
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)
dz_dy = t.gradient(z, y)
print(dz_dy)

tf.Tensor(8.0, shape=(), dtype=float32)


In [17]:
x = tf.ones((2,2))
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)
dy_dx = t.gradient(y, x)
print(dy_dx)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [21]:
x = tf.constant([[1,1],[1,1]], dtype=float)
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)
dy_dx = t.gradient(y, x)

In [22]:
print(dy_dx)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [23]:
x = tf.constant([[2,2],[2,2]], dtype=float)
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)
dy_dx = t.gradient(y, x)

In [24]:
print(dy_dx)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [25]:
x = tf.constant([[2,2],[2,2]], dtype=float)
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)
dz_dx = t.gradient(z, x)
print(dz_dx)

tf.Tensor(
[[16. 16.]
 [16. 16.]], shape=(2, 2), dtype=float32)


In [26]:
print(z)

tf.Tensor(64.0, shape=(), dtype=float32)


In [27]:
print(y)

tf.Tensor(8.0, shape=(), dtype=float32)


In [28]:
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y = x * x
    z = y * y
dz_dx = t.gradient(z, x)  # 108.0 (4*x^3 at x = 3), dy_dx = 2x, dz_dy = 2y = 2x^2
dy_dx = t.gradient(y, x)  # 6.0 
del t

In [29]:
print(dz_dx)

tf.Tensor(108.0, shape=(), dtype=float32)


In [30]:
print(dy_dx)

tf.Tensor(6.0, shape=(), dtype=float32)


In [31]:
4*27

108

In [32]:
def f(x, y):
    output = 1.0
    for i in range(y):
        if i > 1 and i < 5:
            output = tf.multiply(output, x)
    return output


In [36]:
print(f(2, 10))

tf.Tensor(8.0, shape=(), dtype=float32)


In [37]:
def grad(x, y):
    with tf.GradientTape() as t:
        t.watch(x)
        out = f(x, y)
    return t.gradient(out, x)

In [38]:
x = tf.convert_to_tensor(2.0)

In [39]:
assert grad(x, 6).numpy() == 12.0
assert grad(x, 5).numpy() == 12.0
assert grad(x, 4).numpy() == 4.0

In [40]:
x = tf.Variable(1.0)  # Create a Tensorflow variable initialized to 1.0

with tf.GradientTape() as t:
    with tf.GradientTape() as t2:
        y = x * x * x
  # Compute the gradient inside the 't' context manager
  # which means the gradient computation is differentiable as well.
    dy_dx = t2.gradient(y, x)
d2y_dx2 = t.gradient(dy_dx, x)

assert dy_dx.numpy() == 3.0 # dy_dx = 3*x^2 at x=1
assert d2y_dx2.numpy() == 6.0 # d